spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    loadbalancer:
      retry:
        enabled: false # 是否开启Spring Cloud的重试功能
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
          #trustedX509Certificates:
          #- cacerts.pem          
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary, RETAIN_FIRST
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 30
          redis-rate-limiter.burstCapacity: 60
          redis-rate-limiter.requestedTokens: 1
          key-resolver: "#{@ipKeyResolver}"
      routes:
        - id: oauth-login
          uri: lb://uaa-server
          predicates:
            - Path=/api-uaa/oauth/token
          filters:
            - name: PasswordDecoder
            - PreserveHostHeader
            - StripPrefix=1
        - id: auth
          uri: lb://uaa-server
          predicates:
            - Path=/api-uaa/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: auth-login-page
          uri: lb://uaa-server
          predicates:
            - Path=/login.html
          filters:
            - PreserveHostHeader
        - id: auth-login-process
          uri: lb://uaa-server
          predicates:
            - Path=/user/login
          filters:
            - PreserveHostHeader
        - id: auth-login-token
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/token
          filters:
            - PreserveHostHeader
        - id: auth-login-authorize
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/authorize
          filters:
            - PreserveHostHeader
        - id: auth-check-process
          uri: lb://uaa-server
          predicates:
            - Path=/oauth/check_token
          filters:
            - PreserveHostHeader
        - id: user
          uri: lb://${sdps.user.center.serviceId}
          predicates:
            # 转发该路径
            - Path=/api-user/**
          filters:
            # 为了适配前端,将路径切掉一级
            - StripPrefix=1
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000   #默认值为 -1，此时Hystrix 不会向队列内存放作业。即默认hystrix是不会使用队列的
      maximumSize: 1000    #最大线程池大小
      allowMaximumSizeToDivergeFromCoreSize: true   #是否允许队列满之后新建线程到达到最大线程数。默认值为false，当队列满后就执行降级方法
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
sdps:
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-uaa/oauth/**,
        /api-uaa/captcha/**,
        /api-uaa/validata/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /login.html,
        /user/login,
        /actuator/**,
        /api-route/**,
        /favicon.ico,
        /api-user/doc.html,
        /api-user/swagger-resources,
        /api-user/v2/api-docs/**,
        /api-user/webjars/**,
        /api-uaa/system/auth/social-auth-redirect
        /api-user/system/tenant/get-id-by-name
        
    auth:
      encodeKey: sdps842651379000
      licenseUrls: >
        /license-client/client/**,
        /api-user/users/current,
        /api-uaa/oauth/token,
        /api-uaa/captcha/**,
        /api-uaa/validata/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /login.html,
        /user/login,
        /actuator/**,
        /api-user/UC30/UC3018,
        /api-user/menus/findAlls,
        /api-user/menus/saveOrUpdate,
        /api-uaa/oauth/remove/token,
        /api-user/menus/current
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current
        #白名单
        includeClientIds:
          - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
          - webApp
    cores:
      allows:
        - http://127.0.0.1:7003
