package com.sdps.module.system.service.errorcode;

import java.util.Date;
import java.util.List;

import javax.validation.Valid;

import com.sdps.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import com.sdps.module.system.api.errorcode.dto.ErrorCodeRespDTO;

/**
 * 错误码 Service 接口
 *
 * @author 芋道源码
 */
public interface SysErrorCodeService {

	/**
	 * 自动创建错误码
	 *
	 * @param autoGenerateDTOs
	 *            错误码信息
	 */
	void autoGenerateErrorCodes(
			@Valid List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs);

	/**
	 * 增量获得错误码数组
	 *
	 * 如果 minUpdateTime 为空时，则获取所有错误码
	 *
	 * @param applicationName
	 *            应用名
	 * @param minUpdateTime
	 *            最小更新时间
	 * @return 错误码数组
	 */
	List<ErrorCodeRespDTO> getErrorCodeList(String applicationName,
			Date minUpdateTime);

}
