package com.sdps.module.system.api.errorcode;

import java.util.Date;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Service;

import com.sdps.module.system.api.errorcode.ErrorCodeApi;
import com.sdps.module.system.api.errorcode.dto.ErrorCodeAutoGenerateReqDTO;
import com.sdps.module.system.api.errorcode.dto.ErrorCodeRespDTO;
import com.sdps.module.system.service.errorcode.SysErrorCodeService;

/**
 * 错误码 Api 实现类
 *
 * @author 芋道源码
 */
@Service
public class ErrorCodeApiImpl implements ErrorCodeApi {

    @Resource
    private SysErrorCodeService errorCodeService;

    @Override
    public void autoGenerateErrorCodes(List<ErrorCodeAutoGenerateReqDTO> autoGenerateDTOs) {
        errorCodeService.autoGenerateErrorCodes(autoGenerateDTOs);
    }

    @Override
    public List<ErrorCodeRespDTO> getErrorCodeList(String applicationName, Date minUpdateTime) {
        return errorCodeService.getErrorCodeList(applicationName, minUpdateTime);
    }

}
