spring:    
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/sdps?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        filters: stat,slf4j,wall

sdps:
  web:
    admin-ui:
      url: http://127.0.0.1:7003/api-user
  security:
    permit-all_urls:
      - /admin-api/system/user/login
  #多租户配置
  tenant:
    enable: true
    ignore-urls:
      - /admin-api/system/user/login
      - /admin-api/system/auth/sms-login
      - /admin-api/system/auth/send-sms-code
    ignoreTables:
      - system_tenant
      - system_tenant_package
      - system_dict_data
      - system_dict_type
      - system_error_code
      - system_menu
      - system_sensitive_word
      - oauth_client_details
      - system_sms_channel
      - system_sms_template
      - system_sms_log
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.sdps.user.mybatis.mapper.SysRoleMapper.findRolesByExample
      - com.seaboxdata.sdps.user.mybatis.mapper.SysMenuMapper.selectList
  sms-code: # 短信验证码相关的配置项
    expire-times: 10m
    send-frequency: 1m
    send-maximum-quantity-per-day: 10
    begin-code: 9999 # 这里配置 9999 的原因是，测试方便。
    end-code: 9999 # 这里配置 9999 的原因是，测试方便。
  access-log: # 访问日志的配置项
    enable: true
  error-code: # 错误码相关配置项
    enable: true
  demo: false # 关闭演示模式
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: 2.0.0
    base-package: com.sdps.module
